spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school_system
    username: root
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
